config/routes.rb
FirehoseHbs::Application.routes.draw do

   root 'static_pages#index'
   resources :pics

end

app/models/pic.rb
class Pic < ActiveRecord::Base
	# ImageUploader defines how to upload
	# :image says where to put the uploaded file
	mount_uploader :image, ImageUploader	
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/pics_controller.rb
class PicsController < ApplicationController

# def edit
# end

	def index
		if params[:emotion].present?
			@pics = Pic.where(:emotion=>params[:emotion])
		else
			@pics = Pic.all
		end
	end

	def new

		@pic = Pic.new

	end

	def create

		@pic = Pic.create( pic_params )
		redirect_to pics_path

	end

	private


	def pic_params
		params.require(:pic).permit(:lesson, :image, :emotion, :learned)
	end

end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
	def index
	end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pics_helper.rb
module PicsHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>FirehoseHbs</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
  <meta name="viewport" content="width=device-width">

</head>
<body>

    <div class="navbar navbar-inverse">
    <div class="navbar-inner">
    <div class="container">
     
    <!-- .btn-navbar is used as the toggle for collapsed navbar content -->
    <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
    <span class="icon-bar"></span>
    <span class="icon-bar"></span>
    <span class="icon-bar"></span>
    </a>
     
    <!-- Be sure to leave the brand out there if you want it shown -->
    <!--- <a class="brand" href="#">Firehose App</a> -->
  	<%= link_to 'Firehose App', root_path, :class => 'brand' %>

    <!-- Everything you want hidden at 940px or less, place within here -->
    <div class="nav-collapse collapse">
    <!-- .nav, .navbar-search, .navbar-form, etc -->
    	<ul class="nav">
    		<li>
    			<%=  link_to 'My App', pics_path %>
          <%=  link_to 'Create App', new_pic_path %>
          
    		</li>
    	</ul>

    </div>
     
    </div>
    </div>
    </div>


<%= yield %>

</body>
</html>

app/views/pics/index.html.erb
<% @pics.each do |pic| %>
	<div class="span6 boxy text-center">

		<h1 class="h1-custom">
			Lesson: <%= pic.lesson %>
		</h1>

<!-- Add the image -->
		<%= image_tag pic.image %>

		<br />
		<h2>
			<!-- link to filter by all pics that has the motion that's the same as this emotion-->
			Emotion: <%= link_to pic.emotion, pics_path(:emotion => pic.emotion) %>
			<br />
		
			Learned: <%= pic.learned %>
			<br />
		</h2>
	</div>
<% end %>

<div class="span6 offset3 text-center">
	<%= link_to 'Launch Again', new_pic_path, :class => 'btn btn-warning btn-large' %>
</div>

<div class="span5 offset4 text-center">
<iframe width="560" height="315" src="//www.youtube.com/embed/PB3RbO7updc" frameborder="0" allowfullscreen>
</iframe>
</div>

app/views/pics/new.html.erb
<div class="span6 offset3 boxy text-center">
	<h1 class="h1-custom">
		Upload another lesson
	</h1>
<!--  @pic says to put the input into pic -->
	<%= simple_form_for @pic do |f| %>

	<br>
	</br>
		<!-- placeholder gives default values for the fields -->
		<%= f.input :lesson, :label => 'Your latest lesson', :placeholder => '1, 2, etc.'%>
		<%= f.input :image, :label => 'Your picture' %>
		<%= f.input :emotion, :label => 'How do you feel?', :placeholder => 'good, bad, etc.' %>
		<%= f.input :learned, :label => 'What did you learn?' , :placeholder => 'HTML5, CSS, Rails, etc.' %>
	<br>
	</br>
	
		<%= submit_tag 'Save', :class => 'btn btn-warning btn-large' %>
	
	<% end %>
</div>

app/views/static_pages/index.html.erb
<div class="span6 offset3 boxy text-center">
	<h1 class="h1-custom"> Hi I'm Gong Ke </h1>
	<br/>
	<h2>I'm having a ton of fun!</h2>

	<br/><br/>
	<%= link_to 'Launch', new_pic_path, :class => 'btn btn-warning btn-large' %>
</div>